### ISSUE TITLE
about translation

### ISSUE THREAD

**Issue by Narukara** [esp-rs/book#67]
Hello!

Are there any plans to translate this book? Can I maintain a Chinese translation?

**Comment by SergioGasquez** [comment]
Hello @Narukara!

Yes, there are some plans to translate the book to Chinese, but after we complete the overhaul and re-organization of the book that we are working on: #59 (feel free to add any suggestion or feedback).

Your help writing and maintaining a Chinese translation is highly appreciated! In my opinion, it would be better to wait until we have the big update finished, otherwise it would require translating it twice basically.

**Comment by Narukara** [comment]
Thanks! I will wait for the update then.

**Comment by SergioGasquez** [comment]
I think we are now in a good state to translate! We just finished the overhaul of the project, the content got revamped, and it's now better formatted too. There are still some pending issues like https://github.com/esp-rs/book/issues/105, https://github.com/esp-rs/book/issues/76 … but those will be addressed in the future.

**Comment by Narukara** [comment]
> I think we are now in a good state to translate! We just finished the overhaul of the project, the content got revamped, and it's now better formatted too. There are still some pending issues like #105, #76 … but those will be addressed in the future.

Thank you for your efforts. I will start translating soon. :+1:

**Comment by SergioGasquez** [comment]
Hi @Narukara! Just saw that your repo is pointing to the latest commit, again thanks for all your work translating the book! Do you think it's in a good state to be included in the translation section?

**Comment by Narukara** [comment]
We've finished translating everything except the last appendix. I think we're good to go. :smiley:
