### ISSUE TITLE
no_std training book

### ISSUE THREAD

**Issue by SergioGasquez** [esp-rs/book#85]
Shall we keep the content of the "no_std" book in this book or should it be an standalone book?

I don't have any hard opinion, what I would like to have is the code available in the repo, so we can have proper CI testing it. But since we already have a "std book" (Ferrous System training) I would do something equivalent (even if the examples are different) for no_std.

**Comment by bjoernQ** [comment]
Given we have a separate book about the "std" approach probably it's not a bad idea. Also, since we have two very different approaches having all the content in one book is a bit confusing, I guess.

Another thing is, in a separate book we go deeper into more advanced topics (e.g. wifi, async). Not sure we should do that in the current book.

Additionally, probably people will go to the book, then decide which approach they want to try and then head over to the specific books.

But to be honest I also don't have a very strong opinion on this. Generally I would be fine with both options

**Comment by SergioGasquez** [comment]
Here is the initial version of the standalone no_std book:
- repo: https://github.com/esp-rs/no_std-training
- book: https://esp-rs.github.io/no_std-training/
